name: flutter_map
description: A Dart implementation of Leaflet for Flutter apps
publish_to: 'none'
version: 0.8.2
authors:
- John Ryan <john.p.ryan4@gmail.com>
homepage: https://github.com/johnpryan/flutter_map

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^1.0.3
  latlong: ^0.6.1
  positioned_tap_detector:
  transparent_image: ^1.0.0
  async: ^2.4.2
  flutter_image: ^3.0.0
  cached_network_image: ^2.4.1
  sqflite: ^1.3.2+1
  path_provider: ^1.6.24
  vector_math: ^2.0.8

dev_dependencies:
  pedantic: ^1.9.2
  flutter_test:
    sdk: flutter
  test: ^1.15.7